export const BACKEND_URL = 'http://localhost:3000'; // Set this to your local network IP (e.g., http://192.168.x.x:3000) for real device testing

export const STORAGE_KEYS = {
  session: 'unisallround.session',
  users: 'unisallround.users',
  exams: 'unisallround.exams',
  tickets: 'unisallround.tickets',
  notifications: 'unisallround.notifications',
};

export const PTA_DOMAINS = [
  'Area Didattica',
  'Servizi agli Studenti',
  'Terza Missione',
  'Risorse Umane',
  'Bibliotecario',
  'Ufficio Stampa',
  'Funzionario Amministrativo',
  'Tecnico di Laboratiorio (IT)',
  'Tecnico di Laboratio(CTF)',
  'Addetto Mensa'
] as const;

export const translations = {
  IT: {
    login: 'Login',
    register: 'Registrati',
    email: 'E-mail istituzionale',
    password: 'Password',
    name: 'Nome',
    surname: 'Cognome',
    department: 'Dipartimento / ufficio',
    degreeCourse: 'Corso di laurea',
    phone: 'Telefono',
    role: 'Tipo utenza',
    rememberMe: 'Resta loggato su questo dispositivo',
    submitLogin: 'Accedi',
    submitRegister: 'Crea account',
    demoHint: '',
    loadingSession: 'Caricamento sessione...',
    univSalerno: 'Università di Salerno',
    home: 'Home',
    campus: 'Campus',
    services: 'Servizi',
    profile: 'Profilo',
    searchPlaceholder: 'Cerca servizi, lezioni, ticket...',
    logout: 'Esci',
    deleteAccount: 'Elimina account',
    confirmDeleteTitle: 'Eliminare account?',
    confirmDeleteMsg: 'L’account verrà rimosso dai dati locali del prototipo.',
    cancel: 'Annulla',
    delete: 'Elimina',
    profileUpdated: 'Profilo aggiornato',
    invalidProfile: 'Dati profilo non validi',
    checkProfileFields: 'Controlla nome, cognome e mail istituzionale.',
    linkNotAvailable: 'Collegamento non disponibile',
    linkError: 'Il dispositivo non riesce ad aprire questo collegamento.',
    hello: 'Ciao',
    welcomeBack: 'Bentornato,',
    welcome: 'Benvenuto in UnisAllRound',
    passedExams: 'Esami superati',
    weightedAvg: 'Media ponderata',
    acquiredCfu: 'CFU acquisiti',
    progress: 'Avanzamento',
    activeCourses: 'Corsi attivi',
    supervisedStudents: 'Studenti seguiti',
    announcementsSent: 'Avvisi inviati',
    officeHours: 'Ricevimento',
    openTickets: 'Ticket aperti',
    tasksToday: 'Interventi oggi',
    workShift: 'Turno',
    highPriority: 'Priorità alta',
    notifications: 'Notifiche',
    notifSubtitle: 'Annunci filtrati in base allo status configurato.',
    searchResultTitle: 'Risultati di ricerca',
    searchResultOpen: 'Apri',
    studentCareer: 'Carriera studente',
    careerSubtitle: 'Inserimento dati e statistiche calcolate dal sistema.',
    examsCount: 'Esami',
    arithmeticAvg: 'Media',
    ponderatedAvg: 'Ponderata',
    cfuCount: 'CFU',
    progressText: 'del percorso da 180 CFU',
    insertExam: 'Inserisci risultato accademico',
    courseLabel: 'Corso',
    cfuLabel: 'CFU',
    gradeLabel: 'Voto',
    saveCareerData: 'Salva dati carriera',
    teachingSection: 'Didattica',
    teachingSubtitle: 'Orari, aule, esiti e collegamenti rapidi.',
    publishedResults: 'Esiti pubblicati',
    accept: 'Accetta',
    reject: 'Rifiuta',
    elearning: 'E-learning',
    library: 'Biblioteca',
    appointment: 'Ricevimento',
    quickLinks: 'Collegamenti rapidi',
    invalidExamAlert: 'Dati esame non validi',
    invalidExamMsg: 'Inserisci corso, CFU positivi e voto tra 18 e 30.',
    toastExamSavedMsg: 'Dati carriera salvati',
    toastExamAcceptedMsg: 'Esito accettato',
    toastExamRejectedMsg: 'Esito rifiutato',
    teacherArea: 'Area docente',
    teacherAreaSubtitle: 'Corsi, aule assegnate, risultati e comunicazioni.',
    publishExamResult: 'Pubblica esito esame',
    studentLabel: 'Studente',
    publishResultBtn: 'Pubblica risultato',
    announcementsToStudents: 'Comunicazioni agli studenti',
    messageLabel: 'Messaggio',
    sendAnnouncementBtn: 'Invia comunicazione',
    officeHoursSetup: 'Ricevimento',
    hoursAndLocationLabel: 'Orari e luogo',
    updateHoursBtn: 'Aggiorna bacheca',
    invalidPublishAlert: 'Pubblicazione non valida',
    invalidPublishMsg: 'Inserisci studente e voto tra 18 e 30.',
    emptyMessageAlert: 'Messaggio vuoto',
    emptyMessageMsg: 'Scrivi una comunicazione da inviare agli studenti.',
    hoursUpdatedAlert: 'Ricevimento aggiornato',
    toastResultPublished: 'Esito pubblicato agli studenti',
    toastAnnouncementSent: 'Comunicazione inviata',
    ptaArea: 'Area PTA',
    ptaAreaSubtitle: 'Orario di lavoro e gestione ticket di supporto.',
    weeklyShift: 'Turno settimanale',
    shiftSubtitle: 'Presidio tecnico-amministrativo campus',
    pendingRequests: 'Richieste in sospeso',
    pendingRequestsSubtitle: 'Accetta, rifiuta o chiudi gli interventi generati dagli utenti.',
    takeTicket: 'Prendi',
    closeTicket: 'Chiudi',
    toastTicketAssigned: 'Ticket in carico',
    toastTicketClosed: 'Ticket chiuso',
    campusTitle: 'Campus',
    campusSubtitle: 'News, meteo, mensa, trasporti e mappa interattiva Fisciano-Baronissi.',
    canteenTitle: 'Mensa',
    canteenSubtitle: 'Menù settimanale e fasce orarie pranzo/cena.',
    weatherTitle: 'Meteo',
    weatherSubtitle: 'Dati in tempo reale dalle sedi dell\'ateneo.',
    weatherLoading: 'Caricamento meteo...',
    weatherError: 'Errore nel caricamento dei dati meteo',
    weatherWind: 'Vento',
    transportTitle: 'Trasporti pubblici',
    transportSubtitle: 'Orari navetta e collegamenti bus per Fisciano e Baronissi.',
    cusTitle: 'CUS Salerno',
    cusSubtitle: 'Attività sportive, orari campi e contatti della segreteria.',
    mapTitle: 'Mappa del Campus',
    mapSubtitle: 'Seleziona i punti d\'interesse sulla mappa.',
    vegLabel: 'Veg',
    newsLabel: 'News di ateneo',
    newsSubtitle: 'Avvisi e comunicazioni ufficiali.',
    servicesTitle: 'Servizi',
    servicesSubtitle: 'Ticket, FAQ, feedback e collegamenti rapidi.',
    bookLibrarySeat: 'Posto biblioteca',
    bookLibrarySeatDetail: 'Apri prenotazione',
    elearningDetail: 'Piattaforma corsi',
    requestPtaSupport: 'Richiedi supporto PTA',
    ticketTitleLabel: 'Titolo',
    ticketLocationLabel: 'Luogo',
    ticketDescLabel: 'Descrizione',
    ticketPriorityLabel: 'Priorità',
    ticketLow: 'Bassa',
    ticketMedium: 'Media',
    ticketHigh: 'Alta',
    submitTicketBtn: 'Invia ticket',
    feedbackTitle: 'Feedback agli sviluppatori',
    feedbackPlaceholder: 'Segnalazione o suggerimento',
    submitFeedbackBtn: 'Invia feedback',
    faqTitle: 'FAQ',
    faqSubtitle: 'Risposte rapide alle domande ricorrenti.',
    ticketIncompleteAlert: 'Ticket incompleto',
    ticketIncompleteMsg: 'Inserisci titolo, luogo e descrizione della richiesta.',
    feedbackEmptyAlert: 'Segnalazione vuota',
    feedbackEmptyMsg: 'Descrivi il problema o il suggerimento per gli sviluppatori.',
    toastTicketCreated: 'Ticket inviato al PTA',
    toastFeedbackSent: 'Feedback inviato agli sviluppatori',
    profileTitle: 'Profilo',
    profileSubtitle: 'Modifica dei dati personali salvati in fase di registrazione.',
    personalDataTitle: 'Dati personali',
    langLabel: 'Lingua',
    saveChangesBtn: 'Salva modifiche',
    authSubtitleText: 'L’app unica per studenti, docenti e personale tecnico-amministrativo dell’Università degli Studi di Salerno.',
    loginFailedText: 'Accesso non riuscito',
    invalidCredentialsText: 'Credenziali errate. Riprova.',
    missingDataText: 'Dati mancanti',
    enterDetailsText: 'Inserisci nome, cognome e password.',
    invalidEmailText: 'E-mail non valida',
    useInstEmailText: 'Usa una mail istituzionale @unisa.it o @studenti.unisa.it.',
    accountExistsText: 'Account già presente',
    emailExistsText: 'Questo indirizzo e-mail risulta già registrato.',
    registrationCompleteText: 'Registrazione completata',
    sessionSavedText: 'Accesso effettuato e sessione salvata',
    noNotifications: 'Nessuna notifica presente',
    studentRole: 'Studente',
    teacherRole: 'Docente',
    ptaRole: 'PTA',
  },
  EN: {
    login: 'Login',
    register: 'Register',
    email: 'Institutional Email',
    password: 'Password',
    name: 'First Name',
    surname: 'Last Name',
    department: 'Department / Office',
    degreeCourse: 'Degree Course',
    phone: 'Phone Number',
    role: 'User Type',
    rememberMe: 'Keep me logged in on this device',
    submitLogin: 'Login',
    submitRegister: 'Create Account',
    demoHint: '',
    loadingSession: 'Loading session...',
    univSalerno: 'University of Salerno',
    home: 'Home',
    campus: 'Campus',
    services: 'Services',
    profile: 'Profile',
    searchPlaceholder: 'Search services, schedules, tickets...',
    logout: 'Logout',
    deleteAccount: 'Delete Account',
    confirmDeleteTitle: 'Delete Account?',
    confirmDeleteMsg: 'The account will be removed from local database.',
    cancel: 'Cancel',
    delete: 'Delete',
    profileUpdated: 'Profile updated',
    invalidProfile: 'Invalid profile data',
    checkProfileFields: 'Check first name, last name and institutional email.',
    linkNotAvailable: 'Link not available',
    linkError: 'The device cannot open this link.',
    hello: 'Hello',
    welcomeBack: 'Welcome back,',
    welcome: 'Welcome to UnisAllRound',
    passedExams: 'Passed exams',
    weightedAvg: 'Weighted average',
    acquiredCfu: 'Acquired CFU',
    progress: 'Progress',
    activeCourses: 'Active courses',
    supervisedStudents: 'Supervised students',
    announcementsSent: 'Announcements sent',
    officeHours: 'Office Hours',
    openTickets: 'Open tickets',
    tasksToday: 'Tasks today',
    workShift: 'Shift',
    highPriority: 'High priority',
    notifications: 'Notifications',
    notifSubtitle: 'Announcements filtered by role.',
    searchResultTitle: 'Search Results',
    searchResultOpen: 'Open',
    studentCareer: 'Student Career',
    careerSubtitle: 'Data entry and statistics calculated by the system.',
    examsCount: 'Exams',
    arithmeticAvg: 'Average',
    ponderatedAvg: 'Weighted',
    cfuCount: 'CFU',
    progressText: 'of the 180 CFU journey',
    insertExam: 'Insert Academic Result',
    courseLabel: 'Course',
    cfuLabel: 'CFU',
    gradeLabel: 'Grade',
    saveCareerData: 'Save Career Data',
    teachingSection: 'Teaching',
    teachingSubtitle: 'Schedules, rooms, results and quick links.',
    publishedResults: 'Published Results',
    accept: 'Accept',
    reject: 'Reject',
    elearning: 'E-learning',
    library: 'Library',
    appointment: 'Office Hours',
    quickLinks: 'Quick Links',
    invalidExamAlert: 'Invalid Exam Data',
    invalidExamMsg: 'Please enter course, positive CFU, and grade between 18 and 30.',
    toastExamSavedMsg: 'Career data saved',
    toastExamAcceptedMsg: 'Result accepted',
    toastExamRejectedMsg: 'Result rejected',
    teacherArea: 'Teacher Area',
    teacherAreaSubtitle: 'Courses, assigned rooms, results and announcements.',
    publishExamResult: 'Publish Exam Result',
    studentLabel: 'Student',
    publishResultBtn: 'Publish Result',
    announcementsToStudents: 'Announcements to Students',
    messageLabel: 'Message',
    sendAnnouncementBtn: 'Send Announcement',
    officeHoursSetup: 'Office Hours',
    hoursAndLocationLabel: 'Hours and Location',
    updateHoursBtn: 'Update Board',
    invalidPublishAlert: 'Invalid Publication',
    invalidPublishMsg: 'Please enter student and grade between 18 and 30.',
    emptyMessageAlert: 'Empty Message',
    emptyMessageMsg: 'Please write an announcement to send to students.',
    hoursUpdatedAlert: 'Office hours updated',
    toastResultPublished: 'Result published to students',
    toastAnnouncementSent: 'Announcement sent',
    ptaArea: 'Staff Area',
    ptaAreaSubtitle: 'Working hours and support ticket management.',
    weeklyShift: 'Weekly Shift',
    shiftSubtitle: 'Campus technical-administrative shift',
    pendingRequests: 'Pending Requests',
    pendingRequestsSubtitle: 'Accept, assign, or close support tickets.',
    takeTicket: 'Assign to me',
    closeTicket: 'Close',
    toastTicketAssigned: 'Ticket assigned',
    toastTicketClosed: 'Ticket closed',
    campusTitle: 'Campus',
    campusSubtitle: 'News, weather, canteen, transport and interactive map.',
    canteenTitle: 'Canteen',
    canteenSubtitle: 'Weekly menu and lunch/dinner hours.',
    weatherTitle: 'Weather',
    weatherSubtitle: 'Real-time weather data from campus sites.',
    weatherLoading: 'Loading weather...',
    weatherError: 'Error loading weather data',
    weatherWind: 'Wind',
    transportTitle: 'Public Transport',
    transportSubtitle: 'Bus and shuttle connection schedules.',
    cusTitle: 'CUS Salerno',
    cusSubtitle: 'Sports activities, court hours and office contacts.',
    mapTitle: 'Campus Map',
    mapSubtitle: 'Select points of interest on the map.',
    vegLabel: 'Veg',
    newsLabel: 'University News',
    newsSubtitle: 'Official notices and announcements.',
    servicesTitle: 'Services',
    servicesSubtitle: 'Tickets, FAQ, feedback and quick links.',
    bookLibrarySeat: 'Library Seat',
    bookLibrarySeatDetail: 'Open booking',
    elearningDetail: 'Course platform',
    requestPtaSupport: 'Request support',
    ticketTitleLabel: 'Title',
    ticketLocationLabel: 'Location',
    ticketDescLabel: 'Description',
    ticketPriorityLabel: 'Priority',
    ticketLow: 'Low',
    ticketMedium: 'Medium',
    ticketHigh: 'High',
    submitTicketBtn: 'Submit Ticket',
    feedbackTitle: 'Developer Feedback',
    feedbackPlaceholder: 'Bug report or suggestion',
    submitFeedbackBtn: 'Submit Feedback',
    faqTitle: 'FAQ',
    faqSubtitle: 'Quick answers to common questions.',
    ticketIncompleteAlert: 'Incomplete Ticket',
    ticketIncompleteMsg: 'Please enter a title, location, and description.',
    feedbackEmptyAlert: 'Empty Feedback',
    feedbackEmptyMsg: 'Please describe the problem or suggestion for developers.',
    toastTicketCreated: 'Ticket submitted to PTA',
    toastFeedbackSent: 'Feedback sent to developers',
    profileTitle: 'Profile',
    profileSubtitle: 'Edit personal details saved during registration.',
    personalDataTitle: 'Personal Data',
    langLabel: 'Language',
    saveChangesBtn: 'Save Changes',
    authSubtitleText: 'The unified app for students, teachers, and technical-administrative staff of the University of Salerno.',
    loginFailedText: 'Login failed',
    invalidCredentialsText: 'Invalid credentials. Please try again.',
    missingDataText: 'Missing data',
    enterDetailsText: 'Please enter first name, last name, and password.',
    invalidEmailText: 'Invalid email',
    useInstEmailText: 'Use an institutional email @unisa.it or @studenti.unisa.it.',
    accountExistsText: 'Account already exists',
    emailExistsText: 'This email address is already registered.',
    registrationCompleteText: 'Registration completed',
    sessionSavedText: 'Login successful and session saved',
    noNotifications: 'No notifications available',
    studentRole: 'Student',
    teacherRole: 'Teacher',
    ptaRole: 'PTA',
  },
};
