import { StyleSheet } from 'react-native';
import { colors, radii, shadow } from './theme';

export const styles = StyleSheet.create({
  fill: {
    flex: 1,
  },
  boot: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  authShell: {
    flex: 1,
    backgroundColor: colors.background,
  },
  authContent: {
    padding: 20,
    paddingBottom: 34,
  },
  authHeader: {
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 22,
  },
  logoMark: {
    width: 58,
    height: 58,
    borderRadius: 18,
    backgroundColor: colors.forest,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  brand: {
    color: colors.ink,
    fontSize: 31,
    fontWeight: '800',
    letterSpacing: 0,
  },
  mutedText: {
    color: colors.muted,
    fontSize: 14,
    marginTop: 8,
  },
  authSubtitle: {
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
    marginTop: 8,
    maxWidth: 420,
  },
  authCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadow,
  },
  appShell: {
    flex: 1,
    backgroundColor: colors.background,
  },
  topBar: {
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  topTitleBlock: {
    flex: 1,
  },
  smallCaps: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  appTitle: {
    color: colors.ink,
    fontSize: 19,
    fontWeight: '800',
    letterSpacing: 0,
  },
  roleBadge: {
    minHeight: 36,
    paddingHorizontal: 10,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  roleBadgeText: {
    fontSize: 13,
    fontWeight: '800',
  },
  searchShell: {
    marginHorizontal: 18,
    minHeight: 46,
    borderRadius: radii.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  searchInput: {
    flex: 1,
    color: colors.ink,
    fontSize: 15,
    paddingVertical: 10,
  },
  searchResults: {
    marginHorizontal: 18,
    marginTop: 8,
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    zIndex: 3,
  },
  searchResultRow: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  searchResultTitle: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '700',
  },
  searchResultMeta: {
    color: colors.teal,
    fontSize: 13,
    fontWeight: '800',
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 8,
    paddingBottom: 106,
  },
  contentWide: {
    maxWidth: 880,
    alignSelf: 'center',
    width: '100%',
  },
  heroPanel: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    borderWidth: 1.5,
    padding: 18,
    flexDirection: 'row',
    gap: 14,
    alignItems: 'flex-start',
    ...shadow,
  },
  heroIcon: {
    width: 54,
    height: 54,
    borderRadius: 16,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  heroText: {
    flex: 1,
  },
  heroKicker: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  heroTitle: {
    color: colors.ink,
    fontSize: 23,
    lineHeight: 28,
    fontWeight: '800',
    letterSpacing: 0,
    marginTop: 3,
  },
  heroSubtitle: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 21,
    marginTop: 8,
  },
  quickGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 14,
  },
  quickGridWide: {
    flexWrap: 'nowrap',
  },
  statCard: {
    flexGrow: 1,
    flexBasis: '47%',
    minHeight: 120,
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
    justifyContent: 'space-between',
  },
  statIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statValue: {
    color: colors.ink,
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: 0,
    marginTop: 8,
  },
  statLabel: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  sectionTitle: {
    marginTop: 24,
    marginBottom: 10,
  },
  sectionHeading: {
    color: colors.ink,
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0,
  },
  sectionSubtitle: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  tileGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  serviceTile: {
    flexGrow: 1,
    flexBasis: '47%',
    minHeight: 122,
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
  },
  tileIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.mint,
    marginBottom: 12,
  },
  tileLabel: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: '800',
  },
  tileDetail: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
    marginBottom: 10,
  },
  cardTitle: {
    color: colors.ink,
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 0,
    marginBottom: 8,
  },
  bodyText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 21,
  },
  formGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  field: {
    flex: 1,
    marginBottom: 12,
  },
  inputLabel: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 6,
  },
  input: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.sm,
    color: colors.ink,
    backgroundColor: '#FBFCFA',
    paddingHorizontal: 12,
    fontSize: 15,
  },
  inputMultiline: {
    minHeight: 92,
    paddingTop: 12,
    lineHeight: 20,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 14,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxOn: {
    backgroundColor: colors.forest,
    borderColor: colors.forest,
  },
  checkboxText: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '700',
  },
  actionButton: {
    minHeight: 48,
    borderRadius: radii.sm,
    backgroundColor: colors.forest,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 14,
    marginTop: 4,
  },
  actionSecondary: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.forest,
  },
  actionDanger: {
    backgroundColor: colors.danger,
  },
  actionText: {
    color: colors.surface,
    fontSize: 15,
    fontWeight: '800',
  },
  actionSecondaryText: {
    color: colors.forest,
  },
  demoStrip: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  demoButton: {
    flexGrow: 1,
    minHeight: 38,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  demoButtonText: {
    color: colors.forest,
    fontWeight: '800',
    fontSize: 13,
  },
  hintText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 8,
  },
  segmented: {
    flexDirection: 'row',
    backgroundColor: colors.background,
    borderRadius: radii.sm,
    padding: 4,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  segment: {
    flex: 1,
    minHeight: 36,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  segmentActive: {
    backgroundColor: colors.forest,
  },
  segmentText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '800',
  },
  segmentTextActive: {
    color: colors.surface,
  },
  rolePicker: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 14,
  },
  roleOption: {
    flex: 1,
    minHeight: 44,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  roleOptionActive: {
    backgroundColor: colors.forest,
    borderColor: colors.forest,
  },
  roleOptionText: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '800',
  },
  roleOptionTextActive: {
    color: colors.surface,
  },
  listRow: {
    minHeight: 72,
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
    marginBottom: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  listRowCompact: {
    minHeight: 60,
  },
  listIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.mint,
  },
  flexOne: {
    flex: 1,
  },
  rowTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '800',
  },
  rowSubtitle: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 3,
  },
  rowMeta: {
    color: colors.teal,
    fontSize: 12,
    fontWeight: '800',
    marginLeft: 6,
  },
  rowActionText: {
    color: colors.forest,
    fontSize: 12,
    fontWeight: '800',
    marginLeft: 6,
  },
  statsLine: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  statPill: {
    flexGrow: 1,
    flexBasis: '45%',
    borderRadius: radii.sm,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 10,
  },
  statPillValue: {
    color: colors.ink,
    fontSize: 19,
    fontWeight: '800',
  },
  statPillLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
  },
  progressTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: colors.background,
    overflow: 'hidden',
    marginTop: 14,
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: colors.teal,
  },
  progressText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
    marginTop: 8,
  },
  examRow: {
    paddingVertical: 11,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  rowActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    alignItems: 'center',
  },
  iconButton: {
    minHeight: 34,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 5,
  },
  iconButtonDanger: {
    borderColor: colors.coralSoft,
    backgroundColor: colors.coralSoft,
  },
  iconButtonText: {
    color: colors.forest,
    fontSize: 12,
    fontWeight: '800',
  },
  iconButtonTextDanger: {
    color: colors.danger,
  },
  ticketHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  statusBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: '900',
  },
  mapCanvas: {
    height: 230,
    borderRadius: radii.md,
    backgroundColor: colors.sky,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    position: 'relative',
    marginTop: 4,
  },
  mapBandHorizontal: {
    position: 'absolute',
    height: 28,
    left: -20,
    right: -20,
    top: '48%',
    backgroundColor: '#C8D8C4',
    transform: [{ rotate: '-8deg' }],
  },
  mapBandVertical: {
    position: 'absolute',
    width: 28,
    top: -20,
    bottom: -20,
    left: '35%',
    backgroundColor: '#E6DDC9',
    transform: [{ rotate: '12deg' }],
  },
  mapPin: {
    position: 'absolute',
    width: 34,
    height: 34,
    marginLeft: -17,
    marginTop: -17,
    borderRadius: 17,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.forest,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapPinActive: {
    backgroundColor: colors.forest,
    transform: [{ scale: 1.12 }],
  },
  mapDetail: {
    marginTop: 12,
  },
  profileHeader: {
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatar: {
    width: 54,
    height: 54,
    borderRadius: 18,
    backgroundColor: colors.forest,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileName: {
    color: colors.ink,
    fontSize: 19,
    fontWeight: '800',
  },
  dangerZone: {
    gap: 8,
    marginTop: 12,
  },
  bottomNav: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 10,
    minHeight: 70,
    borderRadius: 20,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 6,
    paddingVertical: 8,
    ...shadow,
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  navIconWrap: {
    width: 36,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navIconWrapActive: {
    backgroundColor: colors.forest,
  },
  navText: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '800',
  },
  navTextActive: {
    color: colors.forest,
  },
  badgeDot: {
    position: 'absolute',
    top: -4,
    right: -5,
    minWidth: 17,
    height: 17,
    borderRadius: 9,
    backgroundColor: colors.coral,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  badgeText: {
    color: colors.surface,
    fontSize: 10,
    fontWeight: '900',
  },
  toast: {
    position: 'absolute',
    left: 22,
    right: 22,
    bottom: 92,
    borderRadius: radii.md,
    backgroundColor: colors.ink,
    paddingHorizontal: 14,
    paddingVertical: 12,
    alignItems: 'center',
  },
  toastText: {
    color: colors.surface,
    fontWeight: '800',
    fontSize: 13,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  bellButton: {
    width: 40,
    height: 40,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  bellBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.coral,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  bellBadgeText: {
    color: colors.surface,
    fontSize: 10,
    fontWeight: '900',
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(23, 34, 28, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    width: '100%',
    maxWidth: 500,
    maxHeight: '80%',
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 20,
    ...shadow,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  modalTitle: {
    color: colors.ink,
    fontSize: 20,
    fontWeight: '800',
  },
  modalCloseBtn: {
    padding: 4,
  },
  modalScroll: {
    flexGrow: 0,
  },
  emptyNotificationsText: {
    color: colors.muted,
    fontSize: 15,
    textAlign: 'center',
    paddingVertical: 30,
  },
  cleanGreeting: {
    marginTop: 10,
    marginBottom: 6,
  },
  greetingKicker: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: '700',
  },
  greetingName: {
    color: colors.ink,
    fontSize: 28,
    fontWeight: '800',
    marginTop: 2,
  },
  weatherGrid: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  weatherCard: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
    ...shadow,
  },
  weatherSite: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  weatherMain: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
    marginBottom: 4,
  },
  weatherTemp: {
    color: colors.ink,
    fontSize: 24,
    fontWeight: '800',
  },
  weatherIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.mint,
  },
  weatherCondition: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '700',
  },
  weatherNote: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 2,
  },
  transportCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
    marginBottom: 10,
    ...shadow,
  },
  transportHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  transportInfoBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  transportIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.mint,
    alignItems: 'center',
    justifyContent: 'center',
  },
  transportRouteBlock: {
    flex: 1,
  },
  transportLineNumber: {
    color: colors.forest,
    fontSize: 16,
    fontWeight: '800',
  },
  transportRouteText: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '600',
    marginTop: 2,
  },
  transportExpandedContent: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderColor: colors.border,
  },
  transportPlatformText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  transportDirectionHeader: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '700',
    marginTop: 8,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  transportRunsList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  transportRunChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  transportRunChipActive: {
    borderColor: colors.forest,
    backgroundColor: colors.mint,
  },
  transportRunChipText: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '700',
  },
  transportRunChipTextActive: {
    color: colors.forest,
  },
  transportTimelineContainer: {
    marginTop: 6,
    marginBottom: 10,
    backgroundColor: colors.background,
    borderRadius: radii.sm,
    padding: 12,
  },
  transportTimelineTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.muted,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  transportStopRow: {
    position: 'relative',
    paddingLeft: 22,
    paddingVertical: 8,
  },
  transportStopLine: {
    position: 'absolute',
    left: 4,
    width: 2,
    backgroundColor: colors.forest,
  },
  transportStopNode: {
    position: 'absolute',
    left: 1,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.forest,
    borderWidth: 1.5,
    borderColor: colors.surface,
  },
  transportStopNodeActive: {
    left: 0,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.surface,
    borderColor: colors.forest,
    borderWidth: 2.5,
  },
  transportStopInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  transportStopName: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '500',
    flex: 1,
    paddingRight: 10,
  },
  transportStopTime: {
    color: colors.forest,
    fontSize: 13,
    fontWeight: '700',
  },
});
